SELECT COUNT(2),DEPARTMENT_ID
FROM DBO.S_HREMPLOYEES sh
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING COUNT(2)>1
ORDER BY DEPARTMENT_ID DESC;

SELECT COUNT(1),DEPARTMENT_ID
FROM DBO.S_HREMPLOYEES sh
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING COUNT(1)>1
ORDER BY DEPARTMENT_ID ASC;