select*from DLITHE.DBO.S_HREMPLOYEES
select*from DLITHE.DBO.S_HREMPLOYEES where salary=8000;
select*from DLITHE.DBO.S_HREMPLOYEES where salary>=9000;
select*from DLITHE.DBO.S_HREMPLOYEES where salary<=9000;
select*from DLITHE.DBO.S_HREMPLOYEES where salary!=9000;
select*from DLITHE.DBO.S_HREMPLOYEES where salary<>12008;
select*from DLITHE.DBO.S_HREMPLOYEES where FIRST_NAME IS NULL
select*from DLITHE.DBO.S_HREMPLOYEES where FIRST_NAME IS NOT NULL
select*from DLITHE.DBO.S_HREMPLOYEES where FIRST_NAME IS NULL OR LAST_NAME IS NULL
select*from DLITHE.DBO.S_HREMPLOYEES where FIRST_NAME IS NULL OR LAST_NAME IS NOT NULL
select*from DLITHE.DBO.S_HREMPLOYEES where FIRST_NAME IS NULL AND LAST_NAME IS NULL
select*from DLITHE.DBO.S_HREMPLOYEES where FIRST_NAME IS NULL AND LAST_NAME IS NOT NULL
select*from DLITHE.DBO.S_HREMPLOYEES where EMPLOYEE_ID  IN(101,201,130,140)
select*from DLITHE.DBO.S_HREMPLOYEES where EMPLOYEE_ID NOT IN(101,201,130,140)
select*from DLITHE.DBO.S_HREMPLOYEES where FIRST_NAME LIKE '%A%'AND LAST_NAME LIKE 'V%'
select*from DLITHE.DBO.S_HREMPLOYEES where FIRST_NAME NOT LIKE '%A'
select*from DLITHE.DBO.S_HREMPLOYEES where SALARY BETWEEN 9000 AND 12000
select*from DLITHE.DBO.S_HREMPLOYEES where PHONE_NUMBER not like '%.'
select DISTINCT FIRST_NAME  from DLITHE.DBO.S_HREMPLOYEES



select UPPER(FIRST_NAME) AS FIRST_NAME,LOWER(LAST_NAME),LEN(FIRST_NAME)
from DLITHE.DBO.S_HREMPLOYEES
select rtrim(FIRST_NAME) from DLITHE.DBO.S_HREMPLOYEES
select ltrim(FIRST_NAME) from DLITHE.DBO.S_HREMPLOYEES
select replace('arunagiri','giri','@') from DLITHE.DBO.S_HREMPLOYEES
select SUBSTRING('Arunagiri',1,5) from DLITHE.DBO.S_HREMPLOYEES
select SUBSTRING('arunagiri@307gmail.com',charindex('@','arunagiri@307gmail.com')+1,len('arunagiri@307gmail.com')) from DLITHE.DBO.S_HREMPLOYEES
select CONCAT('arun','a','giri') from DLITHE.DBO.S_HREMPLOYEES

select case when SALARY <=3000 then '3.5lpa'
when SALARY>=5000 then '4lpa'
when SALARY !=10000 then '6lpa'
else 'others'
end as dname from DLITHE.DBO.S_HREMPLOYEES