SELECT * FROM INSURANCE_TARGET_IICS 
SELECT * FROM INSURANCE_IICS 
UPDATE INSURANCE_IICS SET CATEGORY_NAME = 'CARDIAC AND CARDIOTHORACIC SURGERY' WHERE PID =1
SELECT * FROM SCD2_INSURANCE_TARGET 
UPDATE INSURANCE_IICS SET DISTRICT_NAME = 'Vizianagar' WHERE PID =1
-----REPLICATION RESULT--
SELECT * FROM TICKET_IICS

SELECT * FROM SCD1_LOAN
------------AGGRGRATE
SELECT * FROM FA_DELEIVEY_TRUCK fdt 

--SUM---CLAIM AMOUNT
SELECT SUM_SALES FROM SUM_CLAIMAMOUNT 
---COUNT CLAIM AMOUNT
SELECT COUNT  FROM COUNT 

-----MIN--CLAIM AMOUNT

SELECT MIN FROM MIN


---MAX CLAIM AMOUNT

SELECT MAX FROM MAX

---GROUP BY PID CLAIM AMOUNT
SELECT * FROM GROUPBY_PID 
----AVG---CLAIM AMOUNT
SELECT AVG FROM AVG

